# -*- coding: utf-8 -*-
"""Final_Assessment_LVADSUSR_192_Q4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xWJypDpBUgfKLtju9dr1N-SIpWwfJ7yS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
import warnings
warnings.filterwarnings('ignore')
from sklearn import preprocessing

data = pd.read_csv("/content/anomaly_train.csv")

data.head(10)

data.info()

data.columns.tolist()

data.describe()

label_encoder = preprocessing.LabelEncoder()

data['Type'] = label_encoder.fit_transform(data['Type'])

label_encoder = preprocessing.LabelEncoder()

data['Location'] = label_encoder.fit_transform(data['Location'])

#Feature selection
features = data[['User','Amount', 'Type', 'Time', 'Location']]

model = IsolationForest(n_estimators=100, contamination=0.1)
model.fit(features)

y_pred = model.predict(features)

data["anomaly_score"] = model.decision_function(features)
data

#These are the anamolies
anomalies = data.loc[data["anomaly_score"] < 0]
anomalies

anomalies.info()-# There are 100 anamolies in the given data.The finanacial institution need to look into those users.

